version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: enums-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www:cached